services:

  app:
    build: .
    container_name: e-commerce
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
    # 스프링 부트 애플리케이션에 필요한 환경 변수를 설정합니다.
    # Docker Compose의 내부 네트워크를 통해 'redis'라는 서비스 이름으로 Redis 서버에 접속합니다.
    environment:
      # Redis 설정
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

      # JWT 설정
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}

      # Google OAuth2 설정
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}


  # 2. Redis 캐시 서버 서비스 ('redis')
  redis:
    image: redis:alpine
    container_name: my-redis
    restart: on-failure
    ports:
      - "6379:6379"
