# H2 콘솔 비활성화 (보안)
spring:
  h2:
    console:
      enabled: false

# 로깅 레벨 조정 (운영 환경)
logging:
  level:
    root: WARN
    org.springframework.boot: WARN
    com.ecommerce: INFO

# 쿠키 보안 강화
app:
  cookie:
    secure: true  # HTTPS 환경에서만 쿠키 전송
    http-only: true
    same-site: "Strict"

