name: Java Test With Gradle
on:
  push:
      branches:
        - main
        - develop

jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repository code
          uses: actions/checkout@v4

        - name: Setup Java JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: 21
            distribution: "temurin"
            cache: 'gradle'

        - name: application-secret.yml 생성
          env:
            APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YML }}
          run: |
            echo "$APPLICATION_SECRET" > src/main/resources/application-secret.yml

        - name: .env 파일 생성
          env:
            ENV_FILE: ${{ secrets.ENV_FILE }}
          run: |
            echo "$ENV_FILE" > .env
        

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build and run tests With gradle
          run: ./gradlew test

